import { type O11yConfig } from '../types/o11yConfig';

// ────────────────────────────────────────────────────────────────────────────
// Code generator for @ogcio/o11y-sdk-node.
//
// The o11y SDK wraps the OpenTelemetry Node SDK with opinionated defaults
// (gRPC/HTTP exporter, batch processing, URL sampler, PII redaction …).
// The generated output is a single async call to `instrumentNode()`.
// ────────────────────────────────────────────────────────────────────────────

/** npm / yarn / pnpm install command for the o11y SDK. */
export function generateO11yInstallCommand(config: O11yConfig): string {
  const pkg = '@ogcio/o11y-sdk-node';
  switch (config.packageManager) {
    case 'yarn':
      return `yarn add ${pkg}`;
    case 'pnpm':
      return `pnpm add ${pkg}`;
    default:
      return `npm install ${pkg}`;
  }
}

/** Generate the full instrumentation bootstrap file for the o11y SDK. */
export function generateO11yCode(config: O11yConfig): string {
  const ts = config.useTypeScript;
  const lines: string[] = [];

  // ── File header ──────────────────────────────────────────────────────────
  lines.push(`/*****************************************************************************`);
  lines.push(` * o11y SDK Instrumentation — ${config.serviceName}`);
  lines.push(` * Generated by Grafana OTel Instrumentation Generator`);
  lines.push(` *`);
  lines.push(` * Load this file before any other import in your application entry point:`);
  lines.push(` *   import './instrumentation';`);
  lines.push(` *****************************************************************************/`);
  lines.push('');

  // ── Imports ──────────────────────────────────────────────────────────────
  if (ts) {
    lines.push(`import { instrumentNode } from '@ogcio/o11y-sdk-node';`);
    lines.push(`import type { NodeSDKConfig } from '@ogcio/o11y-sdk-node';`);
  } else {
    lines.push(`import { instrumentNode } from '@ogcio/o11y-sdk-node';`);
  }
  lines.push('');

  // ── Config object ─────────────────────────────────────────────────────────
  const configLines: string[] = [];
  const ind = '  ';

  configLines.push(`${ind}collectorUrl: '${config.collectorUrl}',`);
  configLines.push(`${ind}serviceName: '${config.serviceName}',`);
  configLines.push(`${ind}serviceVersion: '${config.serviceVersion}',`);
  configLines.push(`${ind}protocol: '${config.protocol}',`);
  configLines.push(`${ind}collectorMode: '${config.collectorMode}',`);
  configLines.push(`${ind}diagLogLevel: '${config.diagLogLevel}',`);
  configLines.push(`${ind}traceRatio: ${config.traceRatio},`);

  // metrics block
  configLines.push(`${ind}metrics: {`);
  configLines.push(`${ind}  exportIntervalMs: ${config.metricsExportIntervalMs},`);
  configLines.push(`${ind}},`);

  // PII detection block
  configLines.push(`${ind}detection: {`);
  configLines.push(`${ind}  email: ${config.detection.email},`);
  configLines.push(`${ind}  ip: ${config.detection.ip},`);
  configLines.push(`${ind}  ppsn: ${config.detection.ppsn},`);
  configLines.push(`${ind}},`);

  // resource attributes (environment is always included)
  const attrs: Array<[string, string]> = [
    ['deployment.environment', config.environment],
    ...config.resourceAttributes
      .filter(({ key }) => key.trim() !== '')
      .map(({ key, value }) => [key, value] as [string, string]),
  ];
  configLines.push(`${ind}resourceAttributes: {`);
  attrs.forEach(([k, v]) => {
    configLines.push(`${ind}  '${k}': '${v}',`);
  });
  configLines.push(`${ind}},`);

  // span attributes (optional)
  const filledSpanAttrs = config.spanAttributes.filter(({ key }) => key.trim() !== '');
  if (filledSpanAttrs.length > 0) {
    configLines.push(`${ind}spanAttributes: {`);
    filledSpanAttrs.forEach(({ key, value, isFunction }) => {
      const emittedValue = isFunction ? value : `'${value}'`;
      configLines.push(`${ind}  '${key}': ${emittedValue},`);
    });
    configLines.push(`${ind}},`);
  }

  // ignore URLs (optional)
  if (config.ignoreUrls.length > 0) {
    configLines.push(`${ind}ignoreUrls: [`);
    config.ignoreUrls.forEach(({ type, url }) => {
      configLines.push(`${ind}  { type: '${type}', url: '${url}' },`);
    });
    configLines.push(`${ind}],`);
  }

  const typeAnnotation = ts ? ': NodeSDKConfig' : '';
  lines.push(`const sdkConfig${typeAnnotation} = {`);
  lines.push(...configLines);
  lines.push(`};`);
  lines.push('');

  // ── Bootstrap call ────────────────────────────────────────────────────────
  lines.push(`// instrumentNode returns a Promise — await it or call in an async entry point`);
  lines.push(`await instrumentNode(sdkConfig);`);
  lines.push('');

  return lines.join('\n');
}

/** Generate a docker-compose snippet for use with the o11y SDK (gRPC collector). */
export function generateO11yCollectorDockerCompose(config: O11yConfig): string {
  const port = config.protocol === 'grpc' ? '4317' : '4318';
  const comment = config.protocol === 'grpc' ? 'OTLP gRPC receiver' : 'OTLP HTTP receiver';

  const lines = [
    `# OpenTelemetry Collector — Docker Compose`,
    `# Compatible with @ogcio/o11y-sdk-node`,
    `version: '3.8'`,
    `services:`,
    `  otel-collector:`,
    `    image: otel/opentelemetry-collector-contrib:latest`,
    `    command: ["--config", "/etc/otel-collector-config.yaml"]`,
    `    volumes:`,
    `      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml`,
    `    ports:`,
    `      - "${port}:${port}"   # ${comment}`,
    `      - "8888:8888"   # Prometheus metrics (collector)`,
    `      - "8889:8889"   # Prometheus exporter metrics`,
  ];

  return lines.join('\n');
}
